# Generated by Django 5.2.6 on 2025-09-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='numeric_code',
            field=models.IntegerField(db_index=True, help_text='ISO 4217. It is a three-digit numeric currency code. For example: 840', unique=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('WITHDRAW', 'WITHDRAW')], max_length=10),
        ),
    ]
