# Generated by Django 5.2.6 on 2025-09-21 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_system', '0002_alter_currency_numeric_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='settlement_system.wallet'),
        ),
    ]
