# Generated by Django 5.2.6 on 2025-09-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_system', '0003_alter_operation_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(default='Test', help_text='Full name of the currency. For example: "United States Dollar"', max_length=128),
        ),
    ]
