# Generated by Django 5.2.6 on 2025-09-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_system', '0004_alter_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settlement_system.currency'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settlement_system.currency'),
        ),
    ]
